/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 21 18:56:03 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.Position;
import com.google.javascript.jscomp.SourceMap;
import com.google.javascript.rhino.Node;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SourceMap_ESTest extends SourceMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      // Undeclared exception!
      try { 
        sourceMap0.setWrapperPrefix((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.SourceMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      // Undeclared exception!
      try { 
        sourceMap0.addMapping((Node) null, (Position) null, (Position) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.SourceMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      Node node0 = Node.newString("", 4020, 38);
      Object object0 = new Object();
      node0.putProp(38, object0);
      Position position0 = new Position(0, 20);
      // Undeclared exception!
      try { 
        sourceMap0.addMapping(node0, position0, position0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
         //
         verifyException("com.google.javascript.jscomp.SourceMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      sourceMap0.setWrapperPrefix("]\n");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      Node node0 = new Node(44, 44, 44);
      Position position0 = new Position(16, 37);
      sourceMap0.addMapping(node0, position0, position0);
      assertEquals(32, Node.MEMBER_TYPE_PROP);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SourceMap.Mapping sourceMap_Mapping0 = new SourceMap.Mapping();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      sourceMap0.reset();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      sourceMap0.setStartingPosition(0, 0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SourceMap sourceMap0 = new SourceMap();
      // Undeclared exception!
      try { 
        sourceMap0.appendTo((Appendable) null, "");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
