package com.google.javascript.jscomp;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for com.google.javascript.jscomp.UnreachableCodeElimination - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class UnreachableCodeElimination_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("com.google.javascript.jscomp.UnreachableCodeElimination",
            "<init>(com.google.javascript.jscomp.AbstractCompiler,boolean)");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_process(@ForAll("c000") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.UnreachableCodeElimination#process(com.google.javascript.rhino.Node,com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("process(com.google.javascript.rhino.Node,com.google.javascript.rhino.Node)");
    }

}
