package org.apache.commons.cli;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for org.apache.commons.cli.Parser - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class Parser_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("org.apache.commons.cli.Parser",
            "org.apache.commons.cli.BasicParser#<init>()",
            "org.apache.commons.cli.GnuParser#<init>()",
            "org.apache.commons.cli.PosixParser#<init>()");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_checkRequiredOptions(@ForAll("c000") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#checkRequiredOptions()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("checkRequiredOptions()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m001_getOptions(@ForAll("c001") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#getOptions()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c001() {
        return T.calls("getOptions()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m002_getRequiredOptions(@ForAll("c002") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#getRequiredOptions()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c002() {
        return T.calls("getRequiredOptions()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m003_parse(@ForAll("c003") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#parse(org.apache.commons.cli.Options,java.lang.String[])", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c003() {
        return T.calls("parse(org.apache.commons.cli.Options,java.lang.String[])");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m004_parse(@ForAll("c004") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#parse(org.apache.commons.cli.Options,java.lang.String[],boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c004() {
        return T.calls("parse(org.apache.commons.cli.Options,java.lang.String[],boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m005_parse(@ForAll("c005") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#parse(org.apache.commons.cli.Options,java.lang.String[],java.util.Properties)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c005() {
        return T.calls("parse(org.apache.commons.cli.Options,java.lang.String[],java.util.Properties)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m006_parse(@ForAll("c006") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#parse(org.apache.commons.cli.Options,java.lang.String[],java.util.Properties,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c006() {
        return T.calls("parse(org.apache.commons.cli.Options,java.lang.String[],java.util.Properties,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m007_processArgs(@ForAll("c007") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#processArgs(org.apache.commons.cli.Option,java.util.ListIterator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c007() {
        return T.calls("processArgs(org.apache.commons.cli.Option,java.util.ListIterator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m008_processOption(@ForAll("c008") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#processOption(java.lang.String,java.util.ListIterator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c008() {
        return T.calls("processOption(java.lang.String,java.util.ListIterator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m009_processProperties(@ForAll("c009") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#processProperties(java.util.Properties)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c009() {
        return T.calls("processProperties(java.util.Properties)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m010_setOptions(@ForAll("c010") AutoTarget.Call c) {
        T.check("org.apache.commons.cli.Parser#setOptions(org.apache.commons.cli.Options)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c010() {
        return T.calls("setOptions(org.apache.commons.cli.Options)");
    }

}
