package com.google.javascript.jscomp;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for com.google.javascript.jscomp.Compiler - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class Compiler_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("com.google.javascript.jscomp.Compiler",
            "<init>()",
            "<init>(com.google.javascript.jscomp.ErrorManager)");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_acceptConstKeyword(@ForAll("c000") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#acceptConstKeyword()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("acceptConstKeyword()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m001_acceptEcmaScript5(@ForAll("c001") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#acceptEcmaScript5()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c001() {
        return T.calls("acceptEcmaScript5()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m002_addChangeHandler(@ForAll("c002") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#addChangeHandler(com.google.javascript.jscomp.CodeChangeHandler)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c002() {
        return T.calls("addChangeHandler(com.google.javascript.jscomp.CodeChangeHandler)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m003_addIncrementalSourceAst(@ForAll("c003") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#addIncrementalSourceAst(com.google.javascript.jscomp.JsAst)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c003() {
        return T.calls("addIncrementalSourceAst(com.google.javascript.jscomp.JsAst)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m004_addToDebugLog(@ForAll("c004") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#addToDebugLog(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c004() {
        return T.calls("addToDebugLog(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m005_areNodesEqualForInlining(@ForAll("c005") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#areNodesEqualForInlining(com.google.javascript.rhino.Node,com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c005() {
        return T.calls("areNodesEqualForInlining(com.google.javascript.rhino.Node,com.google.javascript.rhino.Node)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m006_buildKnownSymbolTable(@ForAll("c006") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#buildKnownSymbolTable()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c006() {
        return T.calls("buildKnownSymbolTable()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m007_check(@ForAll("c007") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#check()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c007() {
        return T.calls("check()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m008_compile(@ForAll("c008") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c008() {
        return T.calls("compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m009_compile(@ForAll("c009") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c009() {
        return T.calls("compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m010_compile(@ForAll("c010") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c010() {
        return T.calls("compile(com.google.javascript.jscomp.JSSourceFile,com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m011_compile(@ForAll("c011") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c011() {
        return T.calls("compile(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m012_compile(@ForAll("c012") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c012() {
        return T.calls("compile(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m013_compile(@ForAll("c013") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compile(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c013() {
        return T.calls("compile(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m014_compileModules(@ForAll("c014") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#compileModules(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c014() {
        return T.calls("compileModules(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m015_computeCFG(@ForAll("c015") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#computeCFG()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c015() {
        return T.calls("computeCFG()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m016_createPassConfigInternal(@ForAll("c016") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#createPassConfigInternal()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c016() {
        return T.calls("createPassConfigInternal()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m017_disableThreads(@ForAll("c017") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#disableThreads()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c017() {
        return T.calls("disableThreads()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m018_endPass(@ForAll("c018") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#endPass()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c018() {
        return T.calls("endPass()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m019_ensureDefaultPassConfig(@ForAll("c019") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#ensureDefaultPassConfig()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c019() {
        return T.calls("ensureDefaultPassConfig()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m020_getAstDotGraph(@ForAll("c020") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getAstDotGraph()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c020() {
        return T.calls("getAstDotGraph()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m021_getCodingConvention(@ForAll("c021") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getCodingConvention()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c021() {
        return T.calls("getCodingConvention()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m022_getCssRenamingMap(@ForAll("c022") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getCssRenamingMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c022() {
        return T.calls("getCssRenamingMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m023_getDefaultErrorReporter(@ForAll("c023") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getDefaultErrorReporter()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c023() {
        return T.calls("getDefaultErrorReporter()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m024_getDiagnosticGroups(@ForAll("c024") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getDiagnosticGroups()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c024() {
        return T.calls("getDiagnosticGroups()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m025_getErrorCount(@ForAll("c025") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getErrorCount()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c025() {
        return T.calls("getErrorCount()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m026_getErrorLevel(@ForAll("c026") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getErrorLevel(com.google.javascript.jscomp.JSError)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c026() {
        return T.calls("getErrorLevel(com.google.javascript.jscomp.JSError)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m027_getErrorManager(@ForAll("c027") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getErrorManager()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c027() {
        return T.calls("getErrorManager()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m028_getErrors(@ForAll("c028") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getErrors()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c028() {
        return T.calls("getErrors()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m029_getExternsForTesting(@ForAll("c029") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getExternsForTesting()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c029() {
        return T.calls("getExternsForTesting()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m030_getExternsInOrder(@ForAll("c030") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getExternsInOrder()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c030() {
        return T.calls("getExternsInOrder()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m031_getFunctionalInformationMap(@ForAll("c031") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getFunctionalInformationMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c031() {
        return T.calls("getFunctionalInformationMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m032_getGlobalVarReferences(@ForAll("c032") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getGlobalVarReferences()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c032() {
        return T.calls("getGlobalVarReferences()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m033_getInput(@ForAll("c033") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getInput(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c033() {
        return T.calls("getInput(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m034_getInputsForTesting(@ForAll("c034") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getInputsForTesting()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c034() {
        return T.calls("getInputsForTesting()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m035_getInputsInOrder(@ForAll("c035") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getInputsInOrder()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c035() {
        return T.calls("getInputsInOrder()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m036_getMessages(@ForAll("c036") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getMessages()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c036() {
        return T.calls("getMessages()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m037_getModuleGraph(@ForAll("c037") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getModuleGraph()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c037() {
        return T.calls("getModuleGraph()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m038_getNodeForCodeInsertion(@ForAll("c038") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getNodeForCodeInsertion(com.google.javascript.jscomp.JSModule)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c038() {
        return T.calls("getNodeForCodeInsertion(com.google.javascript.jscomp.JSModule)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m039_getOptions(@ForAll("c039") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getOptions()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c039() {
        return T.calls("getOptions()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m040_getParserConfig(@ForAll("c040") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getParserConfig()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c040() {
        return T.calls("getParserConfig()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m041_getPassConfig(@ForAll("c041") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getPassConfig()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c041() {
        return T.calls("getPassConfig()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m042_getPropertyMap(@ForAll("c042") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getPropertyMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c042() {
        return T.calls("getPropertyMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m043_getResult(@ForAll("c043") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getResult()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c043() {
        return T.calls("getResult()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m044_getReverseAbstractInterpreter(@ForAll("c044") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getReverseAbstractInterpreter()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c044() {
        return T.calls("getReverseAbstractInterpreter()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m045_getRoot(@ForAll("c045") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getRoot()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c045() {
        return T.calls("getRoot()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m046_getSourceLine(@ForAll("c046") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getSourceLine(java.lang.String,int)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c046() {
        return T.calls("getSourceLine(java.lang.String,int)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m047_getSourceMap(@ForAll("c047") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getSourceMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c047() {
        return T.calls("getSourceMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m048_getSourceRegion(@ForAll("c048") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getSourceRegion(java.lang.String,int)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c048() {
        return T.calls("getSourceRegion(java.lang.String,int)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m049_getState(@ForAll("c049") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getState()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c049() {
        return T.calls("getState()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m050_getTopScope(@ForAll("c050") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getTopScope()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c050() {
        return T.calls("getTopScope()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m051_getTypeRegistry(@ForAll("c051") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getTypeRegistry()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c051() {
        return T.calls("getTypeRegistry()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m052_getTypeValidator(@ForAll("c052") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getTypeValidator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c052() {
        return T.calls("getTypeValidator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m053_getTypedScopeCreator(@ForAll("c053") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getTypedScopeCreator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c053() {
        return T.calls("getTypedScopeCreator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m054_getUniqueNameIdSupplier(@ForAll("c054") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getUniqueNameIdSupplier()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c054() {
        return T.calls("getUniqueNameIdSupplier()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m055_getVariableMap(@ForAll("c055") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getVariableMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c055() {
        return T.calls("getVariableMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m056_getWarningCount(@ForAll("c056") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getWarningCount()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c056() {
        return T.calls("getWarningCount()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m057_getWarnings(@ForAll("c057") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#getWarnings()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c057() {
        return T.calls("getWarnings()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m058_hasErrors(@ForAll("c058") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#hasErrors()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c058() {
        return T.calls("hasErrors()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m059_hasHaltingErrors(@ForAll("c059") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#hasHaltingErrors()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c059() {
        return T.calls("hasHaltingErrors()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m060_hasRegExpGlobalReferences(@ForAll("c060") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#hasRegExpGlobalReferences()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c060() {
        return T.calls("hasRegExpGlobalReferences()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m061_init(@ForAll("c061") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#init(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c061() {
        return T.calls("init(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSModule[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m062_init(@ForAll("c062") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#init(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c062() {
        return T.calls("init(com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.JSSourceFile[],com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m063_init(@ForAll("c063") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#init(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c063() {
        return T.calls("init(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m064_initCompilerOptionsIfTesting(@ForAll("c064") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#initCompilerOptionsIfTesting()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c064() {
        return T.calls("initCompilerOptionsIfTesting()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m065_initInputsByNameMap(@ForAll("c065") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#initInputsByNameMap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c065() {
        return T.calls("initInputsByNameMap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m066_initModules(@ForAll("c066") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#initModules(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c066() {
        return T.calls("initModules(java.util.List,java.util.List,com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m067_initOptions(@ForAll("c067") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#initOptions(com.google.javascript.jscomp.CompilerOptions)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c067() {
        return T.calls("initOptions(com.google.javascript.jscomp.CompilerOptions)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m068_isIdeMode(@ForAll("c068") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#isIdeMode()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c068() {
        return T.calls("isIdeMode()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m069_isInliningForbidden(@ForAll("c069") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#isInliningForbidden()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c069() {
        return T.calls("isInliningForbidden()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m070_isTypeCheckingEnabled(@ForAll("c070") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#isTypeCheckingEnabled()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c070() {
        return T.calls("isTypeCheckingEnabled()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m071_languageMode(@ForAll("c071") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#languageMode()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c071() {
        return T.calls("languageMode()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m072_newExternInput(@ForAll("c072") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#newExternInput(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c072() {
        return T.calls("newExternInput(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m073_newTracer(@ForAll("c073") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#newTracer(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c073() {
        return T.calls("newTracer(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m074_normalize(@ForAll("c074") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#normalize()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c074() {
        return T.calls("normalize()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m075_optimize(@ForAll("c075") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#optimize()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c075() {
        return T.calls("optimize()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m076_parse(@ForAll("c076") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parse()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c076() {
        return T.calls("parse()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m077_parse(@ForAll("c077") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parse(com.google.javascript.jscomp.JSSourceFile)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c077() {
        return T.calls("parse(com.google.javascript.jscomp.JSSourceFile)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m078_parseInputs(@ForAll("c078") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parseInputs()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c078() {
        return T.calls("parseInputs()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m079_parseSyntheticCode(@ForAll("c079") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parseSyntheticCode(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c079() {
        return T.calls("parseSyntheticCode(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m080_parseSyntheticCode(@ForAll("c080") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parseSyntheticCode(java.lang.String,java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c080() {
        return T.calls("parseSyntheticCode(java.lang.String,java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m081_parseTestCode(@ForAll("c081") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#parseTestCode(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c081() {
        return T.calls("parseTestCode(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m082_precheck(@ForAll("c082") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#precheck()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c082() {
        return T.calls("precheck()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m083_prepareAst(@ForAll("c083") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#prepareAst(com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c083() {
        return T.calls("prepareAst(com.google.javascript.rhino.Node)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m084_process(@ForAll("c084") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#process(com.google.javascript.jscomp.CompilerPass)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c084() {
        return T.calls("process(com.google.javascript.jscomp.CompilerPass)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m085_processDefines(@ForAll("c085") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#processDefines()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c085() {
        return T.calls("processDefines()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m086_rebuildInputsFromModules(@ForAll("c086") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#rebuildInputsFromModules()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c086() {
        return T.calls("rebuildInputsFromModules()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m087_recordFunctionInformation(@ForAll("c087") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#recordFunctionInformation()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c087() {
        return T.calls("recordFunctionInformation()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m088_removeChangeHandler(@ForAll("c088") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#removeChangeHandler(com.google.javascript.jscomp.CodeChangeHandler)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c088() {
        return T.calls("removeChangeHandler(com.google.javascript.jscomp.CodeChangeHandler)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m089_removeExternInput(@ForAll("c089") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#removeExternInput(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c089() {
        return T.calls("removeExternInput(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m090_removeTryCatchFinally(@ForAll("c090") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#removeTryCatchFinally()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c090() {
        return T.calls("removeTryCatchFinally()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m091_replaceIncrementalSourceAst(@ForAll("c091") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#replaceIncrementalSourceAst(com.google.javascript.jscomp.JsAst)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c091() {
        return T.calls("replaceIncrementalSourceAst(com.google.javascript.jscomp.JsAst)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m092_report(@ForAll("c092") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#report(com.google.javascript.jscomp.JSError)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c092() {
        return T.calls("report(com.google.javascript.jscomp.JSError)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m093_reportCodeChange(@ForAll("c093") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#reportCodeChange()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c093() {
        return T.calls("reportCodeChange()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m094_resetUniqueNameId(@ForAll("c094") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#resetUniqueNameId()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c094() {
        return T.calls("resetUniqueNameId()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m095_runCallable(@ForAll("c095") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#runCallable(java.util.concurrent.Callable,boolean,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c095() {
        return T.calls("runCallable(java.util.concurrent.Callable,boolean,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m096_runCallableWithLargeStack(@ForAll("c096") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#runCallableWithLargeStack(java.util.concurrent.Callable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c096() {
        return T.calls("runCallableWithLargeStack(java.util.concurrent.Callable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m097_setCssRenamingMap(@ForAll("c097") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setCssRenamingMap(com.google.javascript.jscomp.CssRenamingMap)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c097() {
        return T.calls("setCssRenamingMap(com.google.javascript.jscomp.CssRenamingMap)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m098_setErrorManager(@ForAll("c098") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setErrorManager(com.google.javascript.jscomp.ErrorManager)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c098() {
        return T.calls("setErrorManager(com.google.javascript.jscomp.ErrorManager)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m099_setHasRegExpGlobalReferences(@ForAll("c099") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setHasRegExpGlobalReferences(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c099() {
        return T.calls("setHasRegExpGlobalReferences(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m100_setLoggingLevel(@ForAll("c100") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setLoggingLevel(java.util.logging.Level)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c100() {
        return T.calls("setLoggingLevel(java.util.logging.Level)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m101_setPassConfig(@ForAll("c101") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setPassConfig(com.google.javascript.jscomp.PassConfig)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c101() {
        return T.calls("setPassConfig(com.google.javascript.jscomp.PassConfig)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m102_setState(@ForAll("c102") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#setState(com.google.javascript.jscomp.Compiler$IntermediateState)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c102() {
        return T.calls("setState(com.google.javascript.jscomp.Compiler$IntermediateState)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m103_startPass(@ForAll("c103") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#startPass(java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c103() {
        return T.calls("startPass(java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m104_stopTracer(@ForAll("c104") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#stopTracer(com.google.javascript.jscomp.Tracer,java.lang.String)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c104() {
        return T.calls("stopTracer(com.google.javascript.jscomp.Tracer,java.lang.String)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m105_stripCode(@ForAll("c105") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#stripCode(java.util.Set,java.util.Set,java.util.Set,java.util.Set)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c105() {
        return T.calls("stripCode(java.util.Set,java.util.Set,java.util.Set,java.util.Set)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m106_throwInternalError(@ForAll("c106") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#throwInternalError(java.lang.String,java.lang.Exception)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c106() {
        return T.calls("throwInternalError(java.lang.String,java.lang.Exception)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m107_toSource(@ForAll("c107") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSource()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c107() {
        return T.calls("toSource()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m108_toSource(@ForAll("c108") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSource(com.google.javascript.jscomp.Compiler$CodeBuilder,int,com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c108() {
        return T.calls("toSource(com.google.javascript.jscomp.Compiler$CodeBuilder,int,com.google.javascript.rhino.Node)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m109_toSource(@ForAll("c109") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSource(com.google.javascript.jscomp.JSModule)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c109() {
        return T.calls("toSource(com.google.javascript.jscomp.JSModule)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m110_toSource(@ForAll("c110") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSource(com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c110() {
        return T.calls("toSource(com.google.javascript.rhino.Node)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m111_toSourceArray(@ForAll("c111") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSourceArray()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c111() {
        return T.calls("toSourceArray()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m112_toSourceArray(@ForAll("c112") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#toSourceArray(com.google.javascript.jscomp.JSModule)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c112() {
        return T.calls("toSourceArray(com.google.javascript.jscomp.JSModule)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m113_updateGlobalVarReferences(@ForAll("c113") AutoTarget.Call c) {
        T.check("com.google.javascript.jscomp.Compiler#updateGlobalVarReferences(java.util.Map,com.google.javascript.rhino.Node)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c113() {
        return T.calls("updateGlobalVarReferences(java.util.Map,com.google.javascript.rhino.Node)");
    }

}
