package org.jfree.chart.plot;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for org.jfree.chart.plot.PiePlot - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class PiePlot_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("org.jfree.chart.plot.PiePlot",
            "<init>()",
            "<init>(org.jfree.data.general.PieDataset)");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_draw(@ForAll("c000") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#draw(java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Point2D,org.jfree.chart.plot.PlotState,org.jfree.chart.plot.PlotRenderingInfo)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("draw(java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Point2D,org.jfree.chart.plot.PlotState,org.jfree.chart.plot.PlotRenderingInfo)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m001_drawItem(@ForAll("c001") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawItem(java.awt.Graphics2D,int,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState,int)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c001() {
        return T.calls("drawItem(java.awt.Graphics2D,int,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState,int)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m002_drawLabels(@ForAll("c002") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawLabels(java.awt.Graphics2D,java.util.List,double,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c002() {
        return T.calls("drawLabels(java.awt.Graphics2D,java.util.List,double,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m003_drawLeftLabel(@ForAll("c003") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawLeftLabel(java.awt.Graphics2D,org.jfree.chart.plot.PiePlotState,org.jfree.chart.plot.PieLabelRecord)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c003() {
        return T.calls("drawLeftLabel(java.awt.Graphics2D,org.jfree.chart.plot.PiePlotState,org.jfree.chart.plot.PieLabelRecord)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m004_drawLeftLabels(@ForAll("c004") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawLeftLabels(org.jfree.data.KeyedValues,java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,float,org.jfree.chart.plot.PiePlotState)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c004() {
        return T.calls("drawLeftLabels(org.jfree.data.KeyedValues,java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,float,org.jfree.chart.plot.PiePlotState)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m005_drawPie(@ForAll("c005") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawPie(java.awt.Graphics2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PlotRenderingInfo)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c005() {
        return T.calls("drawPie(java.awt.Graphics2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PlotRenderingInfo)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m006_drawRightLabel(@ForAll("c006") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawRightLabel(java.awt.Graphics2D,org.jfree.chart.plot.PiePlotState,org.jfree.chart.plot.PieLabelRecord)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c006() {
        return T.calls("drawRightLabel(java.awt.Graphics2D,org.jfree.chart.plot.PiePlotState,org.jfree.chart.plot.PieLabelRecord)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m007_drawRightLabels(@ForAll("c007") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawRightLabels(org.jfree.data.KeyedValues,java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,float,org.jfree.chart.plot.PiePlotState)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c007() {
        return T.calls("drawRightLabels(org.jfree.data.KeyedValues,java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,float,org.jfree.chart.plot.PiePlotState)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m008_drawSimpleLabels(@ForAll("c008") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#drawSimpleLabels(java.awt.Graphics2D,java.util.List,double,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c008() {
        return T.calls("drawSimpleLabels(java.awt.Graphics2D,java.util.List,double,java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlotState)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m009_equals(@ForAll("c009") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#equals(java.lang.Object)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c009() {
        return T.calls("equals(java.lang.Object)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m010_getArcBounds(@ForAll("c010") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getArcBounds(java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,double,double,double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c010() {
        return T.calls("getArcBounds(java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D,double,double,double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m011_getBaseSectionOutlinePaint(@ForAll("c011") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getBaseSectionOutlinePaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c011() {
        return T.calls("getBaseSectionOutlinePaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m012_getBaseSectionOutlineStroke(@ForAll("c012") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getBaseSectionOutlineStroke()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c012() {
        return T.calls("getBaseSectionOutlineStroke()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m013_getBaseSectionPaint(@ForAll("c013") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getBaseSectionPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c013() {
        return T.calls("getBaseSectionPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m014_getDataset(@ForAll("c014") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getDataset()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c014() {
        return T.calls("getDataset()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m015_getDirection(@ForAll("c015") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getDirection()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c015() {
        return T.calls("getDirection()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m016_getExplodePercent(@ForAll("c016") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getExplodePercent(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c016() {
        return T.calls("getExplodePercent(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m017_getIgnoreNullValues(@ForAll("c017") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getIgnoreNullValues()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c017() {
        return T.calls("getIgnoreNullValues()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m018_getIgnoreZeroValues(@ForAll("c018") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getIgnoreZeroValues()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c018() {
        return T.calls("getIgnoreZeroValues()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m019_getInteriorGap(@ForAll("c019") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getInteriorGap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c019() {
        return T.calls("getInteriorGap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m020_getLabelBackgroundPaint(@ForAll("c020") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelBackgroundPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c020() {
        return T.calls("getLabelBackgroundPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m021_getLabelDistributor(@ForAll("c021") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelDistributor()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c021() {
        return T.calls("getLabelDistributor()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m022_getLabelFont(@ForAll("c022") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelFont()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c022() {
        return T.calls("getLabelFont()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m023_getLabelGap(@ForAll("c023") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelGap()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c023() {
        return T.calls("getLabelGap()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m024_getLabelGenerator(@ForAll("c024") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c024() {
        return T.calls("getLabelGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m025_getLabelLinkMargin(@ForAll("c025") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelLinkMargin()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c025() {
        return T.calls("getLabelLinkMargin()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m026_getLabelLinkPaint(@ForAll("c026") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelLinkPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c026() {
        return T.calls("getLabelLinkPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m027_getLabelLinkStroke(@ForAll("c027") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelLinkStroke()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c027() {
        return T.calls("getLabelLinkStroke()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m028_getLabelLinksVisible(@ForAll("c028") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelLinksVisible()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c028() {
        return T.calls("getLabelLinksVisible()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m029_getLabelOutlinePaint(@ForAll("c029") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelOutlinePaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c029() {
        return T.calls("getLabelOutlinePaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m030_getLabelOutlineStroke(@ForAll("c030") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelOutlineStroke()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c030() {
        return T.calls("getLabelOutlineStroke()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m031_getLabelPadding(@ForAll("c031") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelPadding()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c031() {
        return T.calls("getLabelPadding()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m032_getLabelPaint(@ForAll("c032") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c032() {
        return T.calls("getLabelPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m033_getLabelShadowPaint(@ForAll("c033") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLabelShadowPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c033() {
        return T.calls("getLabelShadowPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m034_getLegendItemShape(@ForAll("c034") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLegendItemShape()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c034() {
        return T.calls("getLegendItemShape()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m035_getLegendItems(@ForAll("c035") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLegendItems()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c035() {
        return T.calls("getLegendItems()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m036_getLegendLabelGenerator(@ForAll("c036") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLegendLabelGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c036() {
        return T.calls("getLegendLabelGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m037_getLegendLabelToolTipGenerator(@ForAll("c037") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLegendLabelToolTipGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c037() {
        return T.calls("getLegendLabelToolTipGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m038_getLegendLabelURLGenerator(@ForAll("c038") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getLegendLabelURLGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c038() {
        return T.calls("getLegendLabelURLGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m039_getMaximumExplodePercent(@ForAll("c039") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getMaximumExplodePercent()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c039() {
        return T.calls("getMaximumExplodePercent()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m040_getMaximumLabelWidth(@ForAll("c040") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getMaximumLabelWidth()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c040() {
        return T.calls("getMaximumLabelWidth()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m041_getMinimumArcAngleToDraw(@ForAll("c041") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getMinimumArcAngleToDraw()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c041() {
        return T.calls("getMinimumArcAngleToDraw()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m042_getPieIndex(@ForAll("c042") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getPieIndex()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c042() {
        return T.calls("getPieIndex()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m043_getPlotType(@ForAll("c043") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getPlotType()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c043() {
        return T.calls("getPlotType()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m044_getSectionKey(@ForAll("c044") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSectionKey(int)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c044() {
        return T.calls("getSectionKey(int)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m045_getSectionOutlinePaint(@ForAll("c045") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSectionOutlinePaint(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c045() {
        return T.calls("getSectionOutlinePaint(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m046_getSectionOutlineStroke(@ForAll("c046") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSectionOutlineStroke(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c046() {
        return T.calls("getSectionOutlineStroke(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m047_getSectionOutlinesVisible(@ForAll("c047") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSectionOutlinesVisible()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c047() {
        return T.calls("getSectionOutlinesVisible()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m048_getSectionPaint(@ForAll("c048") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSectionPaint(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c048() {
        return T.calls("getSectionPaint(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m049_getShadowPaint(@ForAll("c049") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getShadowPaint()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c049() {
        return T.calls("getShadowPaint()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m050_getShadowXOffset(@ForAll("c050") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getShadowXOffset()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c050() {
        return T.calls("getShadowXOffset()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m051_getShadowYOffset(@ForAll("c051") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getShadowYOffset()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c051() {
        return T.calls("getShadowYOffset()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m052_getSimpleLabelOffset(@ForAll("c052") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSimpleLabelOffset()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c052() {
        return T.calls("getSimpleLabelOffset()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m053_getSimpleLabels(@ForAll("c053") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getSimpleLabels()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c053() {
        return T.calls("getSimpleLabels()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m054_getStartAngle(@ForAll("c054") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getStartAngle()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c054() {
        return T.calls("getStartAngle()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m055_getToolTipGenerator(@ForAll("c055") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getToolTipGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c055() {
        return T.calls("getToolTipGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m056_getURLGenerator(@ForAll("c056") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#getURLGenerator()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c056() {
        return T.calls("getURLGenerator()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m057_initialise(@ForAll("c057") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#initialise(java.awt.Graphics2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlot,java.lang.Integer,org.jfree.chart.plot.PlotRenderingInfo)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c057() {
        return T.calls("initialise(java.awt.Graphics2D,java.awt.geom.Rectangle2D,org.jfree.chart.plot.PiePlot,java.lang.Integer,org.jfree.chart.plot.PlotRenderingInfo)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m058_isCircular(@ForAll("c058") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#isCircular()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c058() {
        return T.calls("isCircular()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m059_lookupSectionOutlinePaint(@ForAll("c059") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionOutlinePaint(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c059() {
        return T.calls("lookupSectionOutlinePaint(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m060_lookupSectionOutlinePaint(@ForAll("c060") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionOutlinePaint(java.lang.Comparable,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c060() {
        return T.calls("lookupSectionOutlinePaint(java.lang.Comparable,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m061_lookupSectionOutlineStroke(@ForAll("c061") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionOutlineStroke(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c061() {
        return T.calls("lookupSectionOutlineStroke(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m062_lookupSectionOutlineStroke(@ForAll("c062") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionOutlineStroke(java.lang.Comparable,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c062() {
        return T.calls("lookupSectionOutlineStroke(java.lang.Comparable,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m063_lookupSectionPaint(@ForAll("c063") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionPaint(java.lang.Comparable)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c063() {
        return T.calls("lookupSectionPaint(java.lang.Comparable)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m064_lookupSectionPaint(@ForAll("c064") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#lookupSectionPaint(java.lang.Comparable,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c064() {
        return T.calls("lookupSectionPaint(java.lang.Comparable,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m065_setBaseSectionOutlinePaint(@ForAll("c065") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setBaseSectionOutlinePaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c065() {
        return T.calls("setBaseSectionOutlinePaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m066_setBaseSectionOutlineStroke(@ForAll("c066") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setBaseSectionOutlineStroke(java.awt.Stroke)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c066() {
        return T.calls("setBaseSectionOutlineStroke(java.awt.Stroke)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m067_setBaseSectionPaint(@ForAll("c067") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setBaseSectionPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c067() {
        return T.calls("setBaseSectionPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m068_setCircular(@ForAll("c068") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setCircular(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c068() {
        return T.calls("setCircular(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m069_setCircular(@ForAll("c069") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setCircular(boolean,boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c069() {
        return T.calls("setCircular(boolean,boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m070_setDataset(@ForAll("c070") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setDataset(org.jfree.data.general.PieDataset)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c070() {
        return T.calls("setDataset(org.jfree.data.general.PieDataset)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m071_setDirection(@ForAll("c071") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setDirection(org.jfree.chart.util.Rotation)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c071() {
        return T.calls("setDirection(org.jfree.chart.util.Rotation)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m072_setExplodePercent(@ForAll("c072") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setExplodePercent(java.lang.Comparable,double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c072() {
        return T.calls("setExplodePercent(java.lang.Comparable,double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m073_setIgnoreNullValues(@ForAll("c073") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setIgnoreNullValues(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c073() {
        return T.calls("setIgnoreNullValues(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m074_setIgnoreZeroValues(@ForAll("c074") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setIgnoreZeroValues(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c074() {
        return T.calls("setIgnoreZeroValues(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m075_setInteriorGap(@ForAll("c075") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setInteriorGap(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c075() {
        return T.calls("setInteriorGap(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m076_setLabelBackgroundPaint(@ForAll("c076") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelBackgroundPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c076() {
        return T.calls("setLabelBackgroundPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m077_setLabelDistributor(@ForAll("c077") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelDistributor(org.jfree.chart.plot.AbstractPieLabelDistributor)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c077() {
        return T.calls("setLabelDistributor(org.jfree.chart.plot.AbstractPieLabelDistributor)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m078_setLabelFont(@ForAll("c078") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelFont(java.awt.Font)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c078() {
        return T.calls("setLabelFont(java.awt.Font)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m079_setLabelGap(@ForAll("c079") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelGap(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c079() {
        return T.calls("setLabelGap(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m080_setLabelGenerator(@ForAll("c080") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c080() {
        return T.calls("setLabelGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m081_setLabelLinkMargin(@ForAll("c081") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelLinkMargin(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c081() {
        return T.calls("setLabelLinkMargin(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m082_setLabelLinkPaint(@ForAll("c082") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelLinkPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c082() {
        return T.calls("setLabelLinkPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m083_setLabelLinkStroke(@ForAll("c083") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelLinkStroke(java.awt.Stroke)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c083() {
        return T.calls("setLabelLinkStroke(java.awt.Stroke)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m084_setLabelLinksVisible(@ForAll("c084") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelLinksVisible(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c084() {
        return T.calls("setLabelLinksVisible(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m085_setLabelOutlinePaint(@ForAll("c085") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelOutlinePaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c085() {
        return T.calls("setLabelOutlinePaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m086_setLabelOutlineStroke(@ForAll("c086") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelOutlineStroke(java.awt.Stroke)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c086() {
        return T.calls("setLabelOutlineStroke(java.awt.Stroke)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m087_setLabelPadding(@ForAll("c087") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelPadding(org.jfree.chart.util.RectangleInsets)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c087() {
        return T.calls("setLabelPadding(org.jfree.chart.util.RectangleInsets)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m088_setLabelPaint(@ForAll("c088") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c088() {
        return T.calls("setLabelPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m089_setLabelShadowPaint(@ForAll("c089") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLabelShadowPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c089() {
        return T.calls("setLabelShadowPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m090_setLegendItemShape(@ForAll("c090") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLegendItemShape(java.awt.Shape)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c090() {
        return T.calls("setLegendItemShape(java.awt.Shape)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m091_setLegendLabelGenerator(@ForAll("c091") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLegendLabelGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c091() {
        return T.calls("setLegendLabelGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m092_setLegendLabelToolTipGenerator(@ForAll("c092") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLegendLabelToolTipGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c092() {
        return T.calls("setLegendLabelToolTipGenerator(org.jfree.chart.labels.PieSectionLabelGenerator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m093_setLegendLabelURLGenerator(@ForAll("c093") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setLegendLabelURLGenerator(org.jfree.chart.urls.PieURLGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c093() {
        return T.calls("setLegendLabelURLGenerator(org.jfree.chart.urls.PieURLGenerator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m094_setMaximumLabelWidth(@ForAll("c094") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setMaximumLabelWidth(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c094() {
        return T.calls("setMaximumLabelWidth(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m095_setMinimumArcAngleToDraw(@ForAll("c095") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setMinimumArcAngleToDraw(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c095() {
        return T.calls("setMinimumArcAngleToDraw(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m096_setPieIndex(@ForAll("c096") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setPieIndex(int)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c096() {
        return T.calls("setPieIndex(int)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m097_setSectionOutlinePaint(@ForAll("c097") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSectionOutlinePaint(java.lang.Comparable,java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c097() {
        return T.calls("setSectionOutlinePaint(java.lang.Comparable,java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m098_setSectionOutlineStroke(@ForAll("c098") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSectionOutlineStroke(java.lang.Comparable,java.awt.Stroke)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c098() {
        return T.calls("setSectionOutlineStroke(java.lang.Comparable,java.awt.Stroke)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m099_setSectionOutlinesVisible(@ForAll("c099") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSectionOutlinesVisible(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c099() {
        return T.calls("setSectionOutlinesVisible(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m100_setSectionPaint(@ForAll("c100") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSectionPaint(java.lang.Comparable,java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c100() {
        return T.calls("setSectionPaint(java.lang.Comparable,java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m101_setShadowPaint(@ForAll("c101") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setShadowPaint(java.awt.Paint)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c101() {
        return T.calls("setShadowPaint(java.awt.Paint)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m102_setShadowXOffset(@ForAll("c102") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setShadowXOffset(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c102() {
        return T.calls("setShadowXOffset(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m103_setShadowYOffset(@ForAll("c103") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setShadowYOffset(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c103() {
        return T.calls("setShadowYOffset(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m104_setSimpleLabelOffset(@ForAll("c104") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSimpleLabelOffset(org.jfree.chart.util.RectangleInsets)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c104() {
        return T.calls("setSimpleLabelOffset(org.jfree.chart.util.RectangleInsets)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m105_setSimpleLabels(@ForAll("c105") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setSimpleLabels(boolean)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c105() {
        return T.calls("setSimpleLabels(boolean)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m106_setStartAngle(@ForAll("c106") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setStartAngle(double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c106() {
        return T.calls("setStartAngle(double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m107_setToolTipGenerator(@ForAll("c107") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setToolTipGenerator(org.jfree.chart.labels.PieToolTipGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c107() {
        return T.calls("setToolTipGenerator(org.jfree.chart.labels.PieToolTipGenerator)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m108_setURLGenerator(@ForAll("c108") AutoTarget.Call c) {
        T.check("org.jfree.chart.plot.PiePlot#setURLGenerator(org.jfree.chart.urls.PieURLGenerator)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c108() {
        return T.calls("setURLGenerator(org.jfree.chart.urls.PieURLGenerator)");
    }

    @Provide
    Arbitrary<Recipe> receiver() {
        return T.receivers();
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void contract_equalsHashCode(@ForAll("receiver") Recipe r) {
        T.checkEqualsContract(r);
    }

}
