package org.apache.commons.math.complex;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for org.apache.commons.math.complex.Complex - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class Complex_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("org.apache.commons.math.complex.Complex",
            "<init>(double,double)");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_abs(@ForAll("c000") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#abs()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("abs()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m001_acos(@ForAll("c001") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#acos()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c001() {
        return T.calls("acos()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m002_add(@ForAll("c002") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#add(org.apache.commons.math.complex.Complex)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c002() {
        return T.calls("add(org.apache.commons.math.complex.Complex)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m003_asin(@ForAll("c003") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#asin()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c003() {
        return T.calls("asin()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m004_atan(@ForAll("c004") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#atan()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c004() {
        return T.calls("atan()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m005_conjugate(@ForAll("c005") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#conjugate()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c005() {
        return T.calls("conjugate()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m006_cos(@ForAll("c006") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#cos()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c006() {
        return T.calls("cos()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m007_cosh(@ForAll("c007") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#cosh()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c007() {
        return T.calls("cosh()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m008_createComplex(@ForAll("c008") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#createComplex(double,double)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c008() {
        return T.calls("createComplex(double,double)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m009_divide(@ForAll("c009") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#divide(org.apache.commons.math.complex.Complex)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c009() {
        return T.calls("divide(org.apache.commons.math.complex.Complex)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m010_equals(@ForAll("c010") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#equals(java.lang.Object)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c010() {
        return T.calls("equals(java.lang.Object)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m011_exp(@ForAll("c011") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#exp()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c011() {
        return T.calls("exp()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m012_getImaginary(@ForAll("c012") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#getImaginary()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c012() {
        return T.calls("getImaginary()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m013_getReal(@ForAll("c013") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#getReal()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c013() {
        return T.calls("getReal()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m014_hashCode(@ForAll("c014") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#hashCode()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c014() {
        return T.calls("hashCode()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m015_isInfinite(@ForAll("c015") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#isInfinite()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c015() {
        return T.calls("isInfinite()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m016_isNaN(@ForAll("c016") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#isNaN()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c016() {
        return T.calls("isNaN()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m017_log(@ForAll("c017") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#log()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c017() {
        return T.calls("log()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m018_multiply(@ForAll("c018") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#multiply(org.apache.commons.math.complex.Complex)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c018() {
        return T.calls("multiply(org.apache.commons.math.complex.Complex)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m019_negate(@ForAll("c019") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#negate()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c019() {
        return T.calls("negate()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m020_pow(@ForAll("c020") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#pow(org.apache.commons.math.complex.Complex)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c020() {
        return T.calls("pow(org.apache.commons.math.complex.Complex)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m021_sin(@ForAll("c021") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#sin()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c021() {
        return T.calls("sin()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m022_sinh(@ForAll("c022") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#sinh()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c022() {
        return T.calls("sinh()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m023_sqrt(@ForAll("c023") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#sqrt()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c023() {
        return T.calls("sqrt()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m024_sqrt1z(@ForAll("c024") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#sqrt1z()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c024() {
        return T.calls("sqrt1z()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m025_subtract(@ForAll("c025") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#subtract(org.apache.commons.math.complex.Complex)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c025() {
        return T.calls("subtract(org.apache.commons.math.complex.Complex)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m026_tan(@ForAll("c026") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#tan()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c026() {
        return T.calls("tan()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m027_tanh(@ForAll("c027") AutoTarget.Call c) {
        T.check("org.apache.commons.math.complex.Complex#tanh()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c027() {
        return T.calls("tanh()");
    }

    @Provide
    Arbitrary<Recipe> receiver() {
        return T.receivers();
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void contract_equalsHashCode(@ForAll("receiver") Recipe r) {
        T.checkEqualsContract(r);
    }

}
