package org.apache.commons.math.optimization.linear;

import net.jqwik.api.*;
import pbt.auto.*;

/** AUTO-GENERATED by pbt.auto.Generate for org.apache.commons.math.optimization.linear.SimplexSolver - do not edit.
 *  One regression property per public method (snapshot recorded on the fixed version) + contracts. */
public class SimplexSolver_AutoPbtTest {

    static final AutoTarget T = AutoTarget.of("org.apache.commons.math.optimization.linear.SimplexSolver",
            "<init>()",
            "<init>(double)");

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m000_doIteration(@ForAll("c000") AutoTarget.Call c) {
        T.check("org.apache.commons.math.optimization.linear.SimplexSolver#doIteration(org.apache.commons.math.optimization.linear.SimplexTableau)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c000() {
        return T.calls("doIteration(org.apache.commons.math.optimization.linear.SimplexTableau)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m001_doOptimize(@ForAll("c001") AutoTarget.Call c) {
        T.check("org.apache.commons.math.optimization.linear.SimplexSolver#doOptimize()", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c001() {
        return T.calls("doOptimize()");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m002_isOptimal(@ForAll("c002") AutoTarget.Call c) {
        T.check("org.apache.commons.math.optimization.linear.SimplexSolver#isOptimal(org.apache.commons.math.optimization.linear.SimplexTableau)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c002() {
        return T.calls("isOptimal(org.apache.commons.math.optimization.linear.SimplexTableau)");
    }

    @Property(shrinking = ShrinkingMode.OFF, edgeCases = EdgeCasesMode.NONE)
    void m003_solvePhase1(@ForAll("c003") AutoTarget.Call c) {
        T.check("org.apache.commons.math.optimization.linear.SimplexSolver#solvePhase1(org.apache.commons.math.optimization.linear.SimplexTableau)", c);
    }

    @Provide
    Arbitrary<AutoTarget.Call> c003() {
        return T.calls("solvePhase1(org.apache.commons.math.optimization.linear.SimplexTableau)");
    }

}
